# @format

name: Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  FIREFOX_VERSION: 143.0.3

jobs:
  lint-job:
    name: Checking Lint
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Build on ${{ matrix.os }}
        env:
          GO111MODULE: on
          GOOS: linux
        run: |
          make verifiers

  semgrep-static-code-analysis:
    name: "semgrep checks"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out source code
        uses: actions/checkout@v5
      - name: Scanning code on ${{ matrix.os }}
        continue-on-error: false
        run: |
          # Install semgrep rather than using a container due to:
          # https://github.com/actions/checkout/issues/334
          sudo apt install -y python3-pip || apt install -y python3-pip
          pip3 install semgrep
          semgrep --config semgrep.yaml $(pwd)/web-app --error

  ui-assets:
    name: "React Code Has No Warnings & Prettified"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Read .nvmrc
        id: node_version
        run: echo "$(cat .nvmrc)" && echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NVMRC }}
          cache: "yarn"
          cache-dependency-path: web-app/yarn.lock
      - uses: actions/cache@v4
        id: assets-cache
        name: Assets Cache
        with:
          path: |
            ./web-app/build/
          key: ${{ runner.os }}-assets-${{ github.run_id }}
      - name: Install Dependencies
        working-directory: ./web-app
        continue-on-error: false
        run: |
          yarn install --immutable
      - name: Check for Warnings in build output
        working-directory: ./web-app
        continue-on-error: false
        run: |
          ./check-warnings.sh
      - name: Check if Files are Prettified
        working-directory: ./web-app
        continue-on-error: false
        run: |
          ./check-prettier.sh
      - name: Check for dead code
        working-directory: ./web-app
        continue-on-error: false
        run: |
          ./check-deadcode.sh

  swagger-codegen:
    name: "Check for uncommitted changes through Swagger Codegen Changes."
    needs:
      - lint-job
      - ui-assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Read .nvmrc
        id: node_version
        run: echo "$(cat .nvmrc)" && echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NVMRC }}
          cache: "yarn"
          cache-dependency-path: web-app/yarn.lock
      - name: Install NPM Dependencies
        working-directory: ./web-app
        continue-on-error: false
        run: |
          yarn install --immutable
      - name: Install go-swagger
        run: |
          go install github.com/go-swagger/go-swagger/cmd/swagger@latest
          swagger version
      - name: Validate swagger.yml
        run: swagger validate ./swagger.yml
      - name: Run Swagger Codegen
        run: make swagger-gen

      - name: Check for uncommitted changes
        id: git-status
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Codegen modified files. Please run "make swagger-gen" and commit the changes first:"
            git status --porcelain
            echo "##### Git Diff: #####"
            git --no-pager diff
            exit 1
          else
            echo "No changes detected after codegen."
          fi

  latest-minio:
    name: Test Build latest MinIO with Console
    needs:
      - swagger-codegen
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        go-version: [1.24.x]
    steps:
      # Clone Console Repo
      - name: Check out code
        uses: actions/checkout@v5
      # To build minio image, we need to clone the repository first
      - name: Clone github.com/minio/minio
        uses: actions/checkout@v5
        with:
          repository: minio/minio
          path: "minio_repository"
      - name: Check-out matching MinIO branch
        env:
          GH_BRANCH: ${{ github.head_ref || github.ref_name }}
          GH_PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
        run: |
          cd $GITHUB_WORKSPACE/minio_repository; 
          GH_PR_ACCOUNT=`echo $GH_PR_REPO | sed "s/\\/.*//"`
          if [ ! -z "$GH_PR_ACCOUNT" ] && [ ! "$GH_PR_ACCOUNT" = "minio" ]; then
            ALTREPO="https://github.com/$GH_PR_ACCOUNT/minio.git"
            echo "Attempting to fetch $ALTREPO..."
            git remote add alt $ALTREPO
            (git fetch alt && git checkout "alt/$GH_BRANCH") || echo "$ALTREPO ($GH_BRANCH) not available, so keeping default repository/branch"
          fi
          cd $GITHUB_WORKSPACE;
      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
        id: go-minio
      - name: Build on ${{ matrix.os }}
        if: steps.minio-latest-cache.outputs.cache-hit != 'true'
        run: |
          cd $GITHUB_WORKSPACE;
          echo "Create Console Frontend Webui Assets"
          cd $GITHUB_WORKSPACE/web-app;
          make yarn-dep
          make build-static-release

          echo "Create minio binary";
          cd $GITHUB_WORKSPACE/minio_repository;

          echo "Replace Console with local repo"
          echo "replace github.com/minio/console => ../" >> go.mod

          echo "updates to go.mod needed; to update it: go mod tidy"
          go mod tidy

          make build;

          cd $GITHUB_WORKSPACE
          cp $GITHUB_WORKSPACE/minio_repository/minio .

      - uses: actions/cache/save@v4
        # skip minio binary cache
        if: false
        id: minio-latest-cache
        name: MinIO Latest Cache
        with:
          path: |
            ./minio
          key: ${{ runner.os }}-minio-latest-${{  github.run_id  }}

      - uses: actions/upload-artifact@v5
        # skip minio binary upload
        if: false
        with:
          name: minio-console-binary
          path: |
            ./minio

  compile-binary:
    name: Compiles on Go ${{ matrix.go-version }} and ${{ matrix.os }}
    needs:
      - lint-job
      - ui-assets
      - semgrep-static-code-analysis
      - swagger-codegen
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
        id: go
      - uses: actions/cache@v4
        name: Console Binary Cache
        with:
          path: |
            ./console
          key: ${{ runner.os }}-binary-${{ github.run_id }}
      - uses: actions/cache@v4
        id: assets-cache
        name: Assets Cache
        with:
          path: |
            ./web-app/build/
          key: ${{ runner.os }}-assets-${{ github.run_id }}
      - name: Build on ${{ matrix.os }}
        env:
          GO111MODULE: on
          GOOS: linux
        run: |
          make console

  cross-compile-1:
    name: Cross compile
    needs:
      - lint-job
      - ui-assets
      - semgrep-static-code-analysis
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Build on ${{ matrix.os }}
        env:
          GO111MODULE: on
          GOOS: linux
        run: |
          make crosscompile arg1="'linux/ppc64le linux/mips64'"

  cross-compile-2:
    name: Cross compile 2
    needs:
      - lint-job
      - ui-assets
      - semgrep-static-code-analysis
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Build on ${{ matrix.os }}
        env:
          GO111MODULE: on
          GOOS: linux
        run: |
          make crosscompile arg1="'linux/arm64 linux/s390x'"

  cross-compile-3:
    name: Cross compile 3
    needs:
      - lint-job
      - ui-assets
      - semgrep-static-code-analysis
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Build on ${{ matrix.os }}
        env:
          GO111MODULE: on
          GOOS: linux
        run: |
          make crosscompile arg1="'darwin/amd64 freebsd/amd64'"

  cross-compile-4:
    name: Cross compile 4
    needs:
      - lint-job
      - ui-assets
      - semgrep-static-code-analysis
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Build on ${{ matrix.os }}
        env:
          GO111MODULE: on
          GOOS: linux
        run: |
          make crosscompile arg1="'windows/amd64 linux/arm'"

  cross-compile-5:
    name: Cross compile 5
    needs:
      - lint-job
      - ui-assets
      - semgrep-static-code-analysis
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Build on ${{ matrix.os }}
        env:
          GO111MODULE: on
          GOOS: linux
        run: |
          make crosscompile arg1="'linux/386 netbsd/amd64'"

  playwright:
    needs:
      - compile-binary-istanbul-coverage
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Read .nvmrc
        id: node_version
        run: echo "$(cat .nvmrc)" && echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NVMRC }}
          cache: "yarn"
          cache-dependency-path: web-app/yarn.lock

      - name: Install dependencies
        run: |
          echo "Install dependencies"
          cd $GITHUB_WORKSPACE/web-app
          yarn init -y
          yarn add -D playwright babel-plugin-istanbul nyc react-app-rewired create-react-app @playwright/test
          echo "yarn install"
          yarn install --no-immutable

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - uses: actions/cache@v4
        name: Console Binary Cache Istanbul Coverage
        with:
          path: |
            ./console
          key: ${{ runner.os }}-binary-istanbul-coverage-${{ github.run_id }}

      - name: Start Console, front-end app and initialize users/policies
        run: |
          (./console server) & (make initialize-permissions)

      - name: Run Playwright tests
        run: |
          echo "Run tests under playwright folder only"
          cd $GITHUB_WORKSPACE/web-app
          yarn remove playwright
          yarn add --dev @playwright/test
          echo "npx playwright test"
          npx playwright test # To run the tests
          echo "npx nyc report"
          npx nyc report # To see report printed in logs as text
          echo "npx nyc report --reporter=html"
          npx playwright test --reporter github # To run the tests
